export const ACTION_LAVEL = {
  SET_ACTION_LAVEL_1: 'SET_ACTION_LAVEL_1',
  SET_ACTION_LAVEL_2: 'SET_ACTION_LAVEL_2',
  SET_ACTION_LAVEL_3: 'SET_ACTION_LAVEL_3',
};

export const ACTION_PRUEBA_PERSIS = {
  SET_ACTION_PRUEBA_PERSIS: 'SET_ACTION_PRUEBA_PERSIS',
};
